# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16DavFTO3LEQ3lDMPr7d8OJsfpW1JG0p6
"""

import requests
import time

url = "https://deepakverma.streamlit.app/bike_sale"

try:
    r = requests.get(url, allow_redirects=True)
    print(f"[{time.ctime()}] Status: {r.status_code}")
except Exception as e:
    print(f"[{time.ctime()}] Error: {e}")